// Code generated for service
// © 2025.
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/kont1n/MSA_Rocket_Factory/order/internal/model"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, order
func (_m *PaymentClient) CreatePayment(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentClient_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type PaymentClient_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *PaymentClient_Expecter) CreatePayment(ctx interface{}, order interface{}) *PaymentClient_CreatePayment_Call {
	return &PaymentClient_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, order)}
}

func (_c *PaymentClient_CreatePayment_Call) Run(run func(ctx context.Context, order *model.Order)) *PaymentClient_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *PaymentClient_CreatePayment_Call) Return(_a0 *model.Order, _a1 error) *PaymentClient_CreatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentClient_CreatePayment_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *PaymentClient_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
