// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: iam/v1/common.proto

package iam_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session - Информация о сессии пользователя
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid - UUID сессии
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// created_at - Время создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at - Время последнего обновления
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// expires_at - Время истечения
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_iam_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// NotificationMethod - Канал уведомлений пользователя
type NotificationMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name - Провайдер: telegram, email, push и т.д.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// target - Адрес/идентификатор назначения (email, чат-id)
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_iam_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// UserInfo - Основная информация о пользователе
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// login - Логин пользователя
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// email - Email пользователя
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// notification_methods - Каналы уведомлений
	NotificationMethods []*NotificationMethod `protobuf:"bytes,3,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_iam_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// User - Полная информация о пользователе
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid - UUID пользователя
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// info - Базовая информация
	Info *UserInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// created_at - Дата создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at - Дата обновления
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_iam_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_iam_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_iam_v1_common_proto protoreflect.FileDescriptor

const file_iam_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13iam/v1/common.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x85\x01\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12M\n" +
	"\x14notification_methods\x18\x03 \x03(\v2\x1a.iam.v1.NotificationMethodR\x13notificationMethods\"\xb6\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04info\x18\x02 \x01(\v2\x10.iam.v1.UserInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBEZCgithub.com/kont1n/MSA_Rocket_Factory/shared/pkg/proto/iam/v1;iam_v1b\x06proto3"

var (
	file_iam_v1_common_proto_rawDescOnce sync.Once
	file_iam_v1_common_proto_rawDescData []byte
)

func file_iam_v1_common_proto_rawDescGZIP() []byte {
	file_iam_v1_common_proto_rawDescOnce.Do(func() {
		file_iam_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_common_proto_rawDesc), len(file_iam_v1_common_proto_rawDesc)))
	})
	return file_iam_v1_common_proto_rawDescData
}

var file_iam_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_iam_v1_common_proto_goTypes = []any{
	(*Session)(nil),               // 0: iam.v1.Session
	(*NotificationMethod)(nil),    // 1: iam.v1.NotificationMethod
	(*UserInfo)(nil),              // 2: iam.v1.UserInfo
	(*User)(nil),                  // 3: iam.v1.User
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_iam_v1_common_proto_depIdxs = []int32{
	4, // 0: iam.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: iam.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: iam.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: iam.v1.UserInfo.notification_methods:type_name -> iam.v1.NotificationMethod
	2, // 4: iam.v1.User.info:type_name -> iam.v1.UserInfo
	4, // 5: iam.v1.User.created_at:type_name -> google.protobuf.Timestamp
	4, // 6: iam.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_iam_v1_common_proto_init() }
func file_iam_v1_common_proto_init() {
	if File_iam_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_common_proto_rawDesc), len(file_iam_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iam_v1_common_proto_goTypes,
		DependencyIndexes: file_iam_v1_common_proto_depIdxs,
		MessageInfos:      file_iam_v1_common_proto_msgTypes,
	}.Build()
	File_iam_v1_common_proto = out.File
	file_iam_v1_common_proto_goTypes = nil
	file_iam_v1_common_proto_depIdxs = nil
}
