// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: iam/v1/user.proto

package iam_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegistrationInfo - Информация для регистрации пользователя
type UserRegistrationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// info - Основная информация пользователя
	Info *UserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// password - Пароль пользователя
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationInfo) Reset() {
	*x = UserRegistrationInfo{}
	mi := &file_iam_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationInfo) ProtoMessage() {}

func (x *UserRegistrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationInfo.ProtoReflect.Descriptor instead.
func (*UserRegistrationInfo) Descriptor() ([]byte, []int) {
	return file_iam_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistrationInfo) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserRegistrationInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterRequest - Запрос на регистрацию пользователя
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// info - Данные для регистрации
	Info          *UserRegistrationInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_iam_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetInfo() *UserRegistrationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// RegisterResponse - Ответ на регистрацию пользователя
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid - UUID созданного пользователя
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_iam_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserRequest - Запрос информации о пользователе
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid - UUID пользователя
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_iam_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserResponse - Ответ с информацией о пользователе
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user - Пользователь
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_iam_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_iam_v1_user_proto protoreflect.FileDescriptor

const file_iam_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x11iam/v1/user.proto\x12\x06iam.v1\x1a\x13iam/v1/common.proto\"X\n" +
	"\x14UserRegistrationInfo\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.iam.v1.UserInfoR\x04info\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x0fRegisterRequest\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.iam.v1.UserRegistrationInfoR\x04info\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"3\n" +
	"\x0fGetUserResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.iam.v1.UserR\x04user2\x88\x01\n" +
	"\vUserService\x12=\n" +
	"\bRegister\x12\x17.iam.v1.RegisterRequest\x1a\x18.iam.v1.RegisterResponse\x12:\n" +
	"\aGetUser\x12\x16.iam.v1.GetUserRequest\x1a\x17.iam.v1.GetUserResponseBEZCgithub.com/kont1n/MSA_Rocket_Factory/shared/pkg/proto/iam/v1;iam_v1b\x06proto3"

var (
	file_iam_v1_user_proto_rawDescOnce sync.Once
	file_iam_v1_user_proto_rawDescData []byte
)

func file_iam_v1_user_proto_rawDescGZIP() []byte {
	file_iam_v1_user_proto_rawDescOnce.Do(func() {
		file_iam_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_user_proto_rawDesc), len(file_iam_v1_user_proto_rawDesc)))
	})
	return file_iam_v1_user_proto_rawDescData
}

var file_iam_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_iam_v1_user_proto_goTypes = []any{
	(*UserRegistrationInfo)(nil), // 0: iam.v1.UserRegistrationInfo
	(*RegisterRequest)(nil),      // 1: iam.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 2: iam.v1.RegisterResponse
	(*GetUserRequest)(nil),       // 3: iam.v1.GetUserRequest
	(*GetUserResponse)(nil),      // 4: iam.v1.GetUserResponse
	(*UserInfo)(nil),             // 5: iam.v1.UserInfo
	(*User)(nil),                 // 6: iam.v1.User
}
var file_iam_v1_user_proto_depIdxs = []int32{
	5, // 0: iam.v1.UserRegistrationInfo.info:type_name -> iam.v1.UserInfo
	0, // 1: iam.v1.RegisterRequest.info:type_name -> iam.v1.UserRegistrationInfo
	6, // 2: iam.v1.GetUserResponse.user:type_name -> iam.v1.User
	1, // 3: iam.v1.UserService.Register:input_type -> iam.v1.RegisterRequest
	3, // 4: iam.v1.UserService.GetUser:input_type -> iam.v1.GetUserRequest
	2, // 5: iam.v1.UserService.Register:output_type -> iam.v1.RegisterResponse
	4, // 6: iam.v1.UserService.GetUser:output_type -> iam.v1.GetUserResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_iam_v1_user_proto_init() }
func file_iam_v1_user_proto_init() {
	if File_iam_v1_user_proto != nil {
		return
	}
	file_iam_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_user_proto_rawDesc), len(file_iam_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_user_proto_goTypes,
		DependencyIndexes: file_iam_v1_user_proto_depIdxs,
		MessageInfos:      file_iam_v1_user_proto_msgTypes,
	}.Build()
	File_iam_v1_user_proto = out.File
	file_iam_v1_user_proto_goTypes = nil
	file_iam_v1_user_proto_depIdxs = nil
}
