{
 "title": "MSA Rocket Factory - Technical Metrics Dashboard",
 "tags": [
  "technical",
  "http",
  "grpc",
  "kafka",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Rate by Endpoint",
   "type": "timeseries",
   "description": "Общее количество HTTP запросов в секунду с детализацией по endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count[5m])) by (http_route) or sum(rate(otelogen_server_request_count[5m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Errors Rate by Endpoint",
   "type": "timeseries",
   "description": "Общее количество ошибок HTTP запросов в секунду с детализацией по endpoint и HTTP кодам ошибок",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_errors_count[5m])) by (http_route, http_response_status_code) or sum(rate(otelogen_server_errors_count[5m])) by (http_route, http_response_status_code)",
     "legendFormat": "{{http_route}} - {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "gRPC Requests Rate by Service",
   "type": "timeseries",
   "description": "Общее количество gRPC запросов в секунду с детализацией по клиентам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_requests_total[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "gRPC Errors Rate by Service",
   "type": "timeseries",
   "description": "Общее количество ошибок gRPC запросов в секунду с детализацией по сервисам и gRPC кодам ошибок",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_request_errors_total[5m])) by (service, grpc_code)",
     "legendFormat": "{{service}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Messages Rate by Topic",
   "type": "timeseries",
   "description": "Общее количество запросов в секунду в Kafka producer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_messages_total[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Errors Rate by Topic",
   "type": "timeseries",
   "description": "Общее количество ошибок в Kafka producer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_messages_failed_total[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Messages Rate by Topic",
   "type": "timeseries",
   "description": "Общее количество запросов в секунду в Kafka consumer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_messages_total[5m])) by (topic, group_id)",
     "legendFormat": "{{topic}} ({{group_id}})"
    }
   ]
  },
  {
   "title": "Kafka Consumer Errors Rate by Topic",
   "type": "timeseries",
   "description": "Общее количество ошибок в Kafka consumer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_messages_failed_total[5m])) by (topic, group_id)",
     "legendFormat": "{{topic}} ({{group_id}})"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "description": "График роста consumer lag",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_offset_lag",
     "legendFormat": "{{topic}} ({{group_id}}) - Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Rebalancing Count",
   "type": "stat",
   "description": "Количество ребалансировок в consumer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_rebalancing_total) by (group_id)",
     "legendFormat": "{{group_id}}"
    }
   ]
  }
 ]
}