// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

package mocks

import (
	"context"

	iamV1 "github.com/kont1n/MSA_Rocket_Factory/shared/pkg/proto/iam/v1"
	"github.com/stretchr/testify/mock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	mock.Mock
}

// NewMockClient creates a new mock instance.
func NewMockClient(t mock.TestingT) *MockClient {
	mock := &MockClient{}
	mock.Test(t)
	return mock
}

// RegisterUser mocks base method.
func (m *MockClient) RegisterUser(ctx context.Context, login, email, password string, notificationMethods []*iamV1.NotificationMethod) (string, error) {
	args := m.Called(ctx, login, email, password, notificationMethods)
	return args.String(0), args.Error(1)
}

// GetUser mocks base method.
func (m *MockClient) GetUser(ctx context.Context, userUUID string) (*iamV1.User, error) {
	args := m.Called(ctx, userUUID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*iamV1.User), args.Error(1)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	args := m.Called()
	return args.Error(0)
}
