// Code generated for service
// © 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kont1n/MSA_Rocket_Factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	service "github.com/kont1n/MSA_Rocket_Factory/order/internal/service"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CancelOrder(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, order interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, order)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 *model.Order, _a1 error) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CreateOrder(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 *model.Order, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderService) GetOrder(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, id interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) PayOrder(ctx context.Context, order *model.Order) (*model.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, order interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, order)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(_a0 *model.Order, _a1 error) *OrderService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(context.Context, *model.Order) (*model.Order, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrderPaidProducer provides a mock function with given fields: producer
func (_m *OrderService) SetOrderPaidProducer(producer service.OrderPaidProducer) {
	_m.Called(producer)
}

// OrderService_SetOrderPaidProducer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrderPaidProducer'
type OrderService_SetOrderPaidProducer_Call struct {
	*mock.Call
}

// SetOrderPaidProducer is a helper method to define mock.On call
//   - producer service.OrderPaidProducer
func (_e *OrderService_Expecter) SetOrderPaidProducer(producer interface{}) *OrderService_SetOrderPaidProducer_Call {
	return &OrderService_SetOrderPaidProducer_Call{Call: _e.mock.On("SetOrderPaidProducer", producer)}
}

func (_c *OrderService_SetOrderPaidProducer_Call) Run(run func(producer service.OrderPaidProducer)) *OrderService_SetOrderPaidProducer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(service.OrderPaidProducer))
	})
	return _c
}

func (_c *OrderService_SetOrderPaidProducer_Call) Return() *OrderService_SetOrderPaidProducer_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderService_SetOrderPaidProducer_Call) RunAndReturn(run func(service.OrderPaidProducer)) *OrderService_SetOrderPaidProducer_Call {
	_c.Run(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderUUID, status
func (_m *OrderService) UpdateOrderStatus(ctx context.Context, orderUUID string, status model.OrderStatus) error {
	ret := _m.Called(ctx, orderUUID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) error); ok {
		r0 = rf(ctx, orderUUID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type OrderService_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - status model.OrderStatus
func (_e *OrderService_Expecter) UpdateOrderStatus(ctx interface{}, orderUUID interface{}, status interface{}) *OrderService_UpdateOrderStatus_Call {
	return &OrderService_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderUUID, status)}
}

func (_c *OrderService_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderUUID string, status model.OrderStatus)) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderService_UpdateOrderStatus_Call) Return(_a0 error) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_UpdateOrderStatus_Call) RunAndReturn(run func(context.Context, string, model.OrderStatus) error) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
