services: # Здесь описываются контейнеры, необходимые для Inventory-сервиса

  inventory-service: # Inventory микросервис
    build:
      context: ../../../
      dockerfile: deploy/docker/inventory/Dockerfile
    
    container_name: inventory-service
    
    env_file:
      - .env
    
    ports:
      - "${GRPC_PORT}:50051"
    
    depends_on:
      mongo-inventory:
        condition: service_healthy
    
    restart: unless-stopped
    
    networks:
      - microservices-net

  mongo-inventory: # Контейнер с MongoDB — используется для хранения данных об инвентаре (например, запчасти, компоненты)
    image: ${MONGO_IMAGE_NAME}
    # Пример: MONGO_IMAGE_NAME=mongo:7.0.5

    container_name: mongo-inventory

    env_file:
      - .env

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "${EXTERNAL_MONGO_PORT}:27017"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase ${MONGO_AUTH_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true
