name: Run Integration Tests

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4.2.2

      - name: 🛠 Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ inputs.go-version }}
          cache: false

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🧩 Set up Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 📌 Install Task
        uses: arduino/setup-task@v2.0.0

      - name: 📄 Подготовка окружения для тестов
        env:
          # PostgreSQL environment variables for tests
          POSTGRES_IMAGE_NAME: postgres:17.0-alpine3.20
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: order-service
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          HTTP_PORT: 8081
          # MongoDB environment variables for tests
          MONGO_IMAGE_NAME: mongo:7.0.5
          MONGO_HOST: mongo
          MONGO_PORT: 27017
          MONGO_DATABASE: inventory-service
          MONGO_INITDB_ROOT_USERNAME: inventory-service-user
          MONGO_INITDB_ROOT_PASSWORD: inventory-service-password
          GRPC_PORT: 50051
        run: |
          echo "📋 Проверка переменных окружения для интеграционных тестов..."
          echo "🐘 PostgreSQL: $POSTGRES_IMAGE_NAME на $POSTGRES_HOST:$POSTGRES_PORT"
          echo "🍃 MongoDB: $MONGO_IMAGE_NAME на $MONGO_HOST:$MONGO_PORT"
          echo "🔧 Порты: HTTP=$HTTP_PORT, gRPC=$GRPC_PORT"
          echo "✅ Окружение подготовлено для интеграционных тестов"

      - name: 🧪 Run integration tests via Taskfile
        env:
          MODULES: ${{ inputs.modules }}
          # PostgreSQL environment variables for tests
          POSTGRES_IMAGE_NAME: postgres:17.0-alpine3.20
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: order-service
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          HTTP_PORT: 8081
          # MongoDB environment variables for tests
          MONGO_IMAGE_NAME: mongo:7.0.5
          MONGO_HOST: mongo
          MONGO_PORT: 27017
          MONGO_DATABASE: inventory-service
          MONGO_INITDB_ROOT_USERNAME: inventory-service-user
          MONGO_INITDB_ROOT_PASSWORD: inventory-service-password
          GRPC_PORT: 50051
        run: |
          echo "🚀 Начало выполнения интеграционных тестов"
          echo "📋 Модули для тестирования: ${{ inputs.modules }}"
          echo "🐹 Версия Go: ${{ inputs.go-version }}"
          echo "🕒 Время запуска: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          echo "🖥️ Runner: ${{ runner.os }}"
          echo ""
          
          # Показываем информацию о Docker
          echo "🐳 Docker информация:"
          docker --version
          docker-compose --version
          echo ""
          
          # Показываем доступные контейнеры перед тестами
          echo "📦 Активные Docker контейнеры перед тестами:"
          docker ps -a || echo "Нет активных контейнеров"
          echo ""
          
          # Запускаем тесты с детализированным логированием
          echo "▶️ Запуск команды: task test-integration"
          echo "========================================"
          
          set +e  # Отключаем автоматический выход при ошибке для детального анализа
          task test-integration
          TEST_EXIT_CODE=$?
          set -e
          
          echo "========================================"
          echo "🏁 Завершение интеграционных тестов"
          echo "📊 Код завершения: $TEST_EXIT_CODE"
          echo "🕒 Время завершения: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          
          # Показываем состояние контейнеров после тестов
          echo ""
          echo "📦 Docker контейнеры после тестов:"
          docker ps -a || echo "Нет активных контейнеров"
          
          # Показываем логи контейнеров при ошибках
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo ""
            echo "❌ ОБНАРУЖЕНЫ ОШИБКИ В ИНТЕГРАЦИОННЫХ ТЕСТАХ"
            echo "🔍 Собираем дополнительную диагностическую информацию:"
            echo ""
            
            # Показываем логи всех контейнеров
            echo "📋 Логи Docker контейнеров:"
            for container in $(docker ps -aq 2>/dev/null || echo ""); do
              if [ ! -z "$container" ]; then
                container_name=$(docker inspect --format='{{.Name}}' $container 2>/dev/null | sed 's/\///' || echo "unknown")
                echo "--- Логи контейнера: $container_name ($container) ---"
                docker logs --tail=50 $container 2>&1 || echo "Не удалось получить логи контейнера $container"
                echo ""
              fi
            done
            
            # Показываем информацию о сети Docker
            echo "🌐 Docker сети:"
            docker network ls || echo "Не удалось получить информацию о сетях"
            echo ""
            
            # Показываем использование ресурсов
            echo "💾 Использование ресурсов:"
            df -h || echo "Не удалось получить информацию о дисковом пространстве"
            free -h || echo "Не удалось получить информацию о памяти"
            echo ""
          else
            echo "✅ ВСЕ ИНТЕГРАЦИОННЫЕ ТЕСТЫ ПРОШЛИ УСПЕШНО"
          fi
          
          echo "========================================"
          exit $TEST_EXIT_CODE

      - name: 🧹 Cleanup Docker containers
        if: always()
        run: |
          echo "🧹 Начало очистки Docker ресурсов..."
          echo "🕒 Время начала очистки: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          
          # Показываем состояние перед очисткой
          echo ""
          echo "📦 Контейнеры перед очисткой:"
          docker ps -a 2>/dev/null || echo "Docker не доступен"
          
          echo ""
          echo "🖼️ Образы перед очисткой:"
          docker images 2>/dev/null || echo "Docker не доступен"
          
          # Выполняем очистку
          echo ""
          echo "🗑️ Удаляем остановленные контейнеры..."
          docker container prune -f 2>/dev/null || echo "Не удалось выполнить очистку контейнеров"
          
          echo "🗑️ Удаляем неиспользуемые образы..."
          docker image prune -f 2>/dev/null || echo "Не удалось выполнить очистку образов"
          
          echo "🗑️ Удаляем неиспользуемые сети..."
          docker network prune -f 2>/dev/null || echo "Не удалось выполнить очистку сетей"
          
          echo "🗑️ Удаляем неиспользуемые тома..."
          docker volume prune -f 2>/dev/null || echo "Не удалось выполнить очистку томов"
          
          # Показываем состояние после очистки
          echo ""
          echo "📦 Контейнеры после очистки:"
          docker ps -a 2>/dev/null || echo "Docker не доступен"
          
          echo ""
          echo "🖼️ Образы после очистки:"
          docker images 2>/dev/null || echo "Docker не доступен"
          
          echo ""
          echo "✅ Очистка Docker ресурсов завершена"
          echo "🕒 Время завершения: $(date '+%Y-%m-%d %H:%M:%S UTC')"